// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: proto/kf.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EntrarPisoRequest es la solicitud para entrar al piso.
type EntrarPisoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estado int32  `protobuf:"varint,1,opt,name=estado,proto3" json:"estado,omitempty"` // El estado de la solicitud.
	ID     int32  `protobuf:"varint,2,opt,name=iD,proto3" json:"iD,omitempty"`         // El identificador.
	Nombre string `protobuf:"bytes,3,opt,name=nombre,proto3" json:"nombre,omitempty"`  // El nombre.
}

func (x *EntrarPisoRequest) Reset() {
	*x = EntrarPisoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntrarPisoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntrarPisoRequest) ProtoMessage() {}

func (x *EntrarPisoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntrarPisoRequest.ProtoReflect.Descriptor instead.
func (*EntrarPisoRequest) Descriptor() ([]byte, []int) {
	return file_proto_kf_proto_rawDescGZIP(), []int{0}
}

func (x *EntrarPisoRequest) GetEstado() int32 {
	if x != nil {
		return x.Estado
	}
	return 0
}

func (x *EntrarPisoRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *EntrarPisoRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

// MovimientoRequest es la solicitud para un movimiento en el piso.
type MovimientoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Piso int32 `protobuf:"varint,1,opt,name=piso,proto3" json:"piso,omitempty"` // El piso solicitado.
}

func (x *MovimientoRequest) Reset() {
	*x = MovimientoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovimientoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovimientoRequest) ProtoMessage() {}

func (x *MovimientoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovimientoRequest.ProtoReflect.Descriptor instead.
func (*MovimientoRequest) Descriptor() ([]byte, []int) {
	return file_proto_kf_proto_rawDescGZIP(), []int{1}
}

func (x *MovimientoRequest) GetPiso() int32 {
	if x != nil {
		return x.Piso
	}
	return 0
}

// EstadoPisoUpdate es la actualización del estado del piso.
type EstadoPisoUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estado int32 `protobuf:"varint,1,opt,name=estado,proto3" json:"estado,omitempty"` // El nuevo estado del piso.
}

func (x *EstadoPisoUpdate) Reset() {
	*x = EstadoPisoUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstadoPisoUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadoPisoUpdate) ProtoMessage() {}

func (x *EstadoPisoUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadoPisoUpdate.ProtoReflect.Descriptor instead.
func (*EstadoPisoUpdate) Descriptor() ([]byte, []int) {
	return file_proto_kf_proto_rawDescGZIP(), []int{2}
}

func (x *EstadoPisoUpdate) GetEstado() int32 {
	if x != nil {
		return x.Estado
	}
	return 0
}

// MontoDineroMercenarioDirectorRequest es la solicitud para obtener el monto de dinero entre el mercenario y el director.
type MontoDineroMercenarioDirectorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     int32  `protobuf:"varint,1,opt,name=iD,proto3" json:"iD,omitempty"`        // El identificador.
	Nombre string `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"` // El nombre.
}

func (x *MontoDineroMercenarioDirectorRequest) Reset() {
	*x = MontoDineroMercenarioDirectorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MontoDineroMercenarioDirectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MontoDineroMercenarioDirectorRequest) ProtoMessage() {}

func (x *MontoDineroMercenarioDirectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MontoDineroMercenarioDirectorRequest.ProtoReflect.Descriptor instead.
func (*MontoDineroMercenarioDirectorRequest) Descriptor() ([]byte, []int) {
	return file_proto_kf_proto_rawDescGZIP(), []int{3}
}

func (x *MontoDineroMercenarioDirectorRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *MontoDineroMercenarioDirectorRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

// MontoDineroDirectorBancoRequest es la solicitud para obtener el monto de dinero entre el director y el banco.
type MontoDineroDirectorBancoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MontoDineroDirectorBancoRequest) Reset() {
	*x = MontoDineroDirectorBancoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kf_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MontoDineroDirectorBancoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MontoDineroDirectorBancoRequest) ProtoMessage() {}

func (x *MontoDineroDirectorBancoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kf_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MontoDineroDirectorBancoRequest.ProtoReflect.Descriptor instead.
func (*MontoDineroDirectorBancoRequest) Descriptor() ([]byte, []int) {
	return file_proto_kf_proto_rawDescGZIP(), []int{4}
}

// RegistroDataNameRequest es la solicitud para registrar DataName.
type RegistroDataNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     int32  `protobuf:"varint,1,opt,name=iD,proto3" json:"iD,omitempty"`        // El identificador.
	Piso   int32  `protobuf:"varint,2,opt,name=piso,proto3" json:"piso,omitempty"`    // El piso.
	Nombre string `protobuf:"bytes,3,opt,name=nombre,proto3" json:"nombre,omitempty"` // El nombre.
}

func (x *RegistroDataNameRequest) Reset() {
	*x = RegistroDataNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kf_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistroDataNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistroDataNameRequest) ProtoMessage() {}

func (x *RegistroDataNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kf_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistroDataNameRequest.ProtoReflect.Descriptor instead.
func (*RegistroDataNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_kf_proto_rawDescGZIP(), []int{5}
}

func (x *RegistroDataNameRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *RegistroDataNameRequest) GetPiso() int32 {
	if x != nil {
		return x.Piso
	}
	return 0
}

func (x *RegistroDataNameRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

// RegistroDataNameResponse es la respuesta a la solicitud de registro de DataName.
type RegistroDataNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // True si el registro fue exitoso, false en caso contrario.
}

func (x *RegistroDataNameResponse) Reset() {
	*x = RegistroDataNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kf_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistroDataNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistroDataNameResponse) ProtoMessage() {}

func (x *RegistroDataNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kf_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistroDataNameResponse.ProtoReflect.Descriptor instead.
func (*RegistroDataNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_kf_proto_rawDescGZIP(), []int{6}
}

func (x *RegistroDataNameResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// RegistroNodoRequest es la solicitud para registrar un nodo.
type RegistroNodoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     int32  `protobuf:"varint,1,opt,name=iD,proto3" json:"iD,omitempty"`        // El identificador.
	Piso   int32  `protobuf:"varint,2,opt,name=piso,proto3" json:"piso,omitempty"`    // El piso.
	Nombre string `protobuf:"bytes,3,opt,name=nombre,proto3" json:"nombre,omitempty"` // El nombre.
}

func (x *RegistroNodoRequest) Reset() {
	*x = RegistroNodoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kf_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistroNodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistroNodoRequest) ProtoMessage() {}

func (x *RegistroNodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kf_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistroNodoRequest.ProtoReflect.Descriptor instead.
func (*RegistroNodoRequest) Descriptor() ([]byte, []int) {
	return file_proto_kf_proto_rawDescGZIP(), []int{7}
}

func (x *RegistroNodoRequest) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *RegistroNodoRequest) GetPiso() int32 {
	if x != nil {
		return x.Piso
	}
	return 0
}

func (x *RegistroNodoRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

// RegistroNodoResponse es la respuesta a la solicitud de registro de un nodo.
type RegistroNodoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // True si el registro fue exitoso, false en caso contrario.
}

func (x *RegistroNodoResponse) Reset() {
	*x = RegistroNodoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kf_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistroNodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistroNodoResponse) ProtoMessage() {}

func (x *RegistroNodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kf_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistroNodoResponse.ProtoReflect.Descriptor instead.
func (*RegistroNodoResponse) Descriptor() ([]byte, []int) {
	return file_proto_kf_proto_rawDescGZIP(), []int{8}
}

func (x *RegistroNodoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// EstadoUpdateResponse es la respuesta a una actualización de estado.
type EstadoUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // True si la actualización fue exitosa, false en caso contrario.
}

func (x *EstadoUpdateResponse) Reset() {
	*x = EstadoUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kf_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstadoUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadoUpdateResponse) ProtoMessage() {}

func (x *EstadoUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kf_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadoUpdateResponse.ProtoReflect.Descriptor instead.
func (*EstadoUpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_kf_proto_rawDescGZIP(), []int{9}
}

func (x *EstadoUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// MontoDineroResponse es la respuesta a la solicitud de monto de dinero.
type MontoDineroResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount float64 `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"` // El monto de dinero.
}

func (x *MontoDineroResponse) Reset() {
	*x = MontoDineroResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_kf_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MontoDineroResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MontoDineroResponse) ProtoMessage() {}

func (x *MontoDineroResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kf_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MontoDineroResponse.ProtoReflect.Descriptor instead.
func (*MontoDineroResponse) Descriptor() ([]byte, []int) {
	return file_proto_kf_proto_rawDescGZIP(), []int{10}
}

func (x *MontoDineroResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_proto_kf_proto protoreflect.FileDescriptor

var file_proto_kf_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6b, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x53, 0x0a, 0x11, 0x45, 0x6e, 0x74, 0x72, 0x61, 0x72,
	0x50, 0x69, 0x73, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x65,
	0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x65, 0x73, 0x74,
	0x61, 0x64, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x22, 0x27, 0x0a, 0x11, 0x4d,
	0x6f, 0x76, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x69, 0x73, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x70, 0x69, 0x73, 0x6f, 0x22, 0x2a, 0x0a, 0x10, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x50, 0x69,
	0x73, 0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x73, 0x74, 0x61,
	0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f,
	0x22, 0x4e, 0x0a, 0x24, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x44, 0x69, 0x6e, 0x65, 0x72, 0x6f, 0x4d,
	0x65, 0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62,
	0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65,
	0x22, 0x21, 0x0a, 0x1f, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x44, 0x69, 0x6e, 0x65, 0x72, 0x6f, 0x44,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x42, 0x61, 0x6e, 0x63, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x55, 0x0a, 0x17, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x44,
	0x61, 0x74, 0x61, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x44, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x69, 0x73, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x69,
	0x73, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x22, 0x34, 0x0a, 0x18, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x22, 0x51, 0x0a, 0x13, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x4e, 0x6f, 0x64, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x69, 0x73, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x69, 0x73, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6e,
	0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d,
	0x62, 0x72, 0x65, 0x22, 0x30, 0x0a, 0x14, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x4e,
	0x6f, 0x64, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x30, 0x0a, 0x14, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x2d, 0x0a, 0x13, 0x4d, 0x6f, 0x6e, 0x74, 0x6f,
	0x44, 0x69, 0x6e, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0xec, 0x04, 0x0a, 0x09, 0x4b, 0x46, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x13, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x61,
	0x72, 0x45, 0x6e, 0x74, 0x72, 0x61, 0x72, 0x50, 0x69, 0x73, 0x6f, 0x12, 0x17, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x61, 0x72, 0x50, 0x69, 0x73, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x73, 0x74, 0x61,
	0x64, 0x6f, 0x50, 0x69, 0x73, 0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x47, 0x0a, 0x13,
	0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x61, 0x72, 0x4d, 0x6f, 0x76, 0x69, 0x6d, 0x69, 0x65,
	0x6e, 0x74, 0x6f, 0x12, 0x17, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x6d,
	0x69, 0x65, 0x6e, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4a, 0x0a, 0x14, 0x41, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x69,
	0x7a, 0x61, 0x72, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x50, 0x69, 0x73, 0x6f, 0x12, 0x16, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x50, 0x69, 0x73, 0x6f, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x45, 0x73, 0x74,
	0x61, 0x64, 0x6f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x6f, 0x0a, 0x26, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x61, 0x72, 0x4d, 0x6f,
	0x6e, 0x74, 0x6f, 0x44, 0x69, 0x6e, 0x65, 0x72, 0x6f, 0x4d, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x61,
	0x72, 0x69, 0x6f, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x2a, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x44, 0x69, 0x6e, 0x65, 0x72, 0x6f, 0x4d, 0x65,
	0x72, 0x63, 0x65, 0x6e, 0x61, 0x72, 0x69, 0x6f, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d,
	0x6f, 0x6e, 0x74, 0x6f, 0x44, 0x69, 0x6e, 0x65, 0x72, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x65, 0x0a, 0x21, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74, 0x61, 0x72, 0x4d,
	0x6f, 0x6e, 0x74, 0x6f, 0x44, 0x69, 0x6e, 0x65, 0x72, 0x6f, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x42, 0x61, 0x6e, 0x63, 0x6f, 0x12, 0x25, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d,
	0x6f, 0x6e, 0x74, 0x6f, 0x44, 0x69, 0x6e, 0x65, 0x72, 0x6f, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x42, 0x61, 0x6e, 0x63, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x44, 0x69, 0x6e, 0x65, 0x72,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5a, 0x0a, 0x19, 0x53, 0x6f, 0x6c,
	0x69, 0x63, 0x69, 0x74, 0x61, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x44, 0x61,
	0x74, 0x61, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x6f, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x15, 0x53, 0x6f, 0x6c, 0x69, 0x63, 0x69, 0x74,
	0x61, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x4e, 0x6f, 0x64, 0x6f, 0x12, 0x19,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x4e, 0x6f,
	0x64, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x6f, 0x4e, 0x6f, 0x64, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_kf_proto_rawDescOnce sync.Once
	file_proto_kf_proto_rawDescData = file_proto_kf_proto_rawDesc
)

func file_proto_kf_proto_rawDescGZIP() []byte {
	file_proto_kf_proto_rawDescOnce.Do(func() {
		file_proto_kf_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_kf_proto_rawDescData)
	})
	return file_proto_kf_proto_rawDescData
}

var file_proto_kf_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_kf_proto_goTypes = []interface{}{
	(*EntrarPisoRequest)(nil),                    // 0: grpc.EntrarPisoRequest
	(*MovimientoRequest)(nil),                    // 1: grpc.MovimientoRequest
	(*EstadoPisoUpdate)(nil),                     // 2: grpc.EstadoPisoUpdate
	(*MontoDineroMercenarioDirectorRequest)(nil), // 3: grpc.MontoDineroMercenarioDirectorRequest
	(*MontoDineroDirectorBancoRequest)(nil),      // 4: grpc.MontoDineroDirectorBancoRequest
	(*RegistroDataNameRequest)(nil),              // 5: grpc.RegistroDataNameRequest
	(*RegistroDataNameResponse)(nil),             // 6: grpc.RegistroDataNameResponse
	(*RegistroNodoRequest)(nil),                  // 7: grpc.RegistroNodoRequest
	(*RegistroNodoResponse)(nil),                 // 8: grpc.RegistroNodoResponse
	(*EstadoUpdateResponse)(nil),                 // 9: grpc.EstadoUpdateResponse
	(*MontoDineroResponse)(nil),                  // 10: grpc.MontoDineroResponse
}
var file_proto_kf_proto_depIdxs = []int32{
	0,  // 0: grpc.KFservice.SolicitarEntrarPiso:input_type -> grpc.EntrarPisoRequest
	1,  // 1: grpc.KFservice.SolicitarMovimiento:input_type -> grpc.MovimientoRequest
	2,  // 2: grpc.KFservice.ActualizarEstadoPiso:input_type -> grpc.EstadoPisoUpdate
	3,  // 3: grpc.KFservice.SolicitarMontoDineroMercenarioDirector:input_type -> grpc.MontoDineroMercenarioDirectorRequest
	4,  // 4: grpc.KFservice.SolicitarMontoDineroDirectorBanco:input_type -> grpc.MontoDineroDirectorBancoRequest
	5,  // 5: grpc.KFservice.SolicitarRegistroDataName:input_type -> grpc.RegistroDataNameRequest
	7,  // 6: grpc.KFservice.SolicitarRegistroNodo:input_type -> grpc.RegistroNodoRequest
	2,  // 7: grpc.KFservice.SolicitarEntrarPiso:output_type -> grpc.EstadoPisoUpdate
	1,  // 8: grpc.KFservice.SolicitarMovimiento:output_type -> grpc.MovimientoRequest
	9,  // 9: grpc.KFservice.ActualizarEstadoPiso:output_type -> grpc.EstadoUpdateResponse
	10, // 10: grpc.KFservice.SolicitarMontoDineroMercenarioDirector:output_type -> grpc.MontoDineroResponse
	10, // 11: grpc.KFservice.SolicitarMontoDineroDirectorBanco:output_type -> grpc.MontoDineroResponse
	6,  // 12: grpc.KFservice.SolicitarRegistroDataName:output_type -> grpc.RegistroDataNameResponse
	8,  // 13: grpc.KFservice.SolicitarRegistroNodo:output_type -> grpc.RegistroNodoResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_kf_proto_init() }
func file_proto_kf_proto_init() {
	if File_proto_kf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_kf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntrarPisoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovimientoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EstadoPisoUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MontoDineroMercenarioDirectorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kf_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MontoDineroDirectorBancoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kf_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistroDataNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kf_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistroDataNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kf_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistroNodoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kf_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistroNodoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kf_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EstadoUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_kf_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MontoDineroResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_kf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kf_proto_goTypes,
		DependencyIndexes: file_proto_kf_proto_depIdxs,
		MessageInfos:      file_proto_kf_proto_msgTypes,
	}.Build()
	File_proto_kf_proto = out.File
	file_proto_kf_proto_rawDesc = nil
	file_proto_kf_proto_goTypes = nil
	file_proto_kf_proto_depIdxs = nil
}
